#!/usr/bin/env python

import sys
import re
from subprocess import check_output

try:
    jira_browse_url = check_output(['git', 'config', '--get', "githook.jiraurl"])[0:-1]
except:
    sys.exit()

try:
    jira_identifier = check_output(['git', 'config', '--get', "githook.jiraidregex"])[0:-1]
except:
    sys.exit()

file_path = sys.argv[1]

with open(file_path, 'r') as f:
    lines = f.readlines()
    oneliner = len(lines) == 1
    msg = "\n".join(filter(lambda x: not x.startswith('#'), lines))

matches = set(re.findall(jira_identifier, msg))

already_present = set(re.findall(r"\[({0})\]\({1}(?:{0})\)".format(jira_identifier, jira_browse_url), msg))
missing_links = matches.difference(already_present)

if len(missing_links) == 0:
    sys.exit()

with open(file_path, 'a') as f:
    if oneliner:
        f.write("\n")
    f.write("\n")
    links = "\n".join(map(lambda x: "[{0}]({1}{0})".format(x, jira_browse_url), matches))
    f.write(links)
