#!/usr/bin/env python

import sys
from subprocess import check_output


try:
    files = check_output(['git', 'ls-files', '--modified'])
    try:
        yaml_files_checks = [(f, check_output(['swagger-tools', 'validate', f])) for f in files.split("\n") if "yaml" in f]
    except CalledProcessError:
        pass
    error_files = [file_check for file_check in yaml_files_checks if file_check[1]]
    for errors in error_files:
        print "\n Found errors in swagger file " + errors[0] + ":\n" + errors[1]

    if error_files:
        sys.exit(1)
except Exception as e:
    #print e
    sys.exit(1)

sys.exit(0)
