#!/usr/bin/env python

import sys
import re
from subprocess import check_output

try:
    symbolic_ref = check_output(['git', 'symbolic-ref', 'HEAD'])
except:
    sys.exit()

try:
    jira_identifier = check_output(['git', 'config', '--get', "githook.jiraidregex"])[0:-1]
except:
    sys.exit()

matched = re.findall(jira_identifier, symbolic_ref)

if len(matched) == 0:
    sys.exit()

branch = matched[0]

with open(sys.argv[1], 'r') as commit_file:
    commit_msg = commit_file.readlines()

if len(filter(lambda x: not x.startswith('#') and not x.strip() =='',
              commit_msg)) > 0:
    sys.exit()

with open(sys.argv[1], 'w') as commit_file:
    commit_file.write(branch + ' ' + "".join(commit_msg))

sys.exit()
